channels:
  - conda-forge
  - defaults
  - andrazpolak
  - https://conda.anaconda.org/pyviz/

dependencies:
  # required
  - numpy
  - python

  - intake-dremio>=0.2.1
  # lint
  - black

  # testing
  - pytest

name: "default"
